### ISSUE TITLE
Cache?

### ISSUE THREAD

**Issue by kentcdodds** [gdi2290/angular2-webpack-seed#1]
Is there a reason for `cache: false`? I think by turning the cache off, it makes webpack rebuild the entire project from scratch each time instead of using a cached version and doing interative builds. As an app grows, this could get pretty painful from a speed perspective. I remove that line and everything seems to be working just fine.

**Comment by gdi2290** [comment]
I did it since I was trying to get it to work initial which meant I had cache'd version of files that I changed or told WebPack not to parse

**Comment by kentcdodds** [comment]
understood :+1:
